[package]
name = "membership"
version = "0.1.0"
authors = ["Maté Antunovic <just.mate.antunovic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "*"
actix-raft = "0.4.3"
serde = "*"
